{{- $usesOsb := (index (.Values.global | default .Values) "osb").atp | default .Values.osb.atp -}}
{{- $oadbService := .Values.secrets.oadbService | default .Values.global.oadbService -}}
{{- $oadbWalletPw := .Values.secrets.oadbWalletPassword | default .Values.global.oadbWalletPassword -}}
{{- $oadbUser := .Values.secrets.oadbUser | default (printf "%s_%s_user" .Release.Namespace .Chart.Name ) | replace "-" "_" | trunc 96 -}}
{{- $oadbPass := .Values.secrets.oadbPassword | default (printf "%s_deFAUlt321#" .Chart.Name) -}}


{{/* ADMIN credentials */}}
{{- if not (or $usesOsb .Values.oadbAdminSecret .Values.global.oadbAdminSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-oadb-admin
  labels: {{ include (printf "%s.labels" .Chart.Name) . | nindent 4 }}
type: Opaque
data:
  oadb_admin_pw: {{ .Values.secrets.oadbAdminPassword | default "" | b64enc | default ("" | quote) }}
{{- end }}


{{/* DB Connection */}}
{{- if not (or $usesOsb .Values.oadbConnectionSecret .Values.global.oadbConnectionSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-oadb-connection
  labels: {{ include (printf "%s.labels" .Chart.Name ) . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.global.mock.service "all" }}
  oadb_wallet_pw: {{ "mock" | b64enc }}
  oadb_service: {{ "mock" | b64enc }}
  {{- else }}
  oadb_wallet_pw: {{ required "Value .secrets.oadbWalletPassword is required!" $oadbWalletPw | b64enc }}
  oadb_service: {{ required "Value .secrets.oadbService is required!" $oadbService | b64enc }}
  {{- end }}
{{- end }}


{{/* DB Schema Credentials */}}
{{- if not (or $usesOsb .Values.oadbUserSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-oadb-credentials
  labels: {{ include (printf "%s.labels" .Chart.Name ) . | nindent 4 }}
type: Opaque
data:
  {{- if eq .Values.global.mock.service "all" }}
  oadb_user: {{ "mock" | b64enc }}
  oadb_pw: {{ "mock" | b64enc }}
  {{- else }}
  oadb_user: {{ $oadbUser | b64enc }}
  oadb_pw: {{ $oadbPass | b64enc }}
  {{- end }}
{{- end }}


{{/* DB Wallet */}}
{{- if not (or $usesOsb .Values.oadbWalletSecret .Values.global.oadbWalletSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-oadb-wallet
  labels: {{ include (printf "%s.labels" .Chart.Name) . | nindent 4 }}
type: Opaque
data:
{{- $globWallet := .Files.Glob (printf "%s*/*" (.Values.secrets.oadbWallet | default "secrets/Wallet" | trimSuffix "/")) }}
{{- ($globWallet).AsSecrets | nindent 2 }}
{{- end }}