global:
  ociAuthSecret: oci-credentials        # OCI authentication credentials secret name
  ossStreamSecret: oss-connection       # Name of Stream Connection secret
  oadbAdminSecret: oadb-admin           # Name of DB Admin secret created earlier
  oadbWalletSecret: oadb-wallet         # Name of wallet secret created earlier
  oadbConnectionSecret: oadb-connection # Name of connection secret created earlier
  mock:
    service: "false"
  osb:
    instanceName: mushop
    atp: true
    oss: true
    objectstorage: true
    objectstoragenamespace: ocitenancyname
    
ingress:
  enabled: true

  hosts:
    - mushop.ateam.cloud
    - insecure.mushop.ateam.cloud

  # Values examples: letsencrypt-prod, letsencrypt-staging, 
  # This controls the cluster issuer what's used in Ingress
  clusterIssuer: letsencrypt-prod

  # Used for ACME registration (if TLS is set)
  email: "no-reply@ateam-oracle.com"

  # If TLS is provided, cert-manager needs to be installed.
  tls: true

api:
  env:
    mediaUrl:                 # Object Storage URL for catalog image assets
    newsletterSubscribeUrl:   # Newsletter subscription endpoint (https://[API_GATEWAY_URL]/newsletter/subscribe)

storefront:
  env:
    odaEnabled:               # Enables the Oracle Digital Assistant as widget on the storefront
    odaUri:                   # Oracle Digital Assistant Channel URI to be used with MuShop
    odaChannelId:             # Oracle Digital Assistant Channel Id to be used with MuShop
    odaSecret:                # Used if client auth is enabled.
    odaUserHiddenInitMessage: # Hidden Init Message if any. Makes the Digital Assistant proactive.