apiVersion: controller.kubeslice.io/v1alpha1
kind: SliceConfig
metadata:
  name: cockroach-slice
spec:
  sliceSubnet: 192.168.0.0/16 
  sliceType: Application
  sliceGatewayProvider:
    sliceGatewayType: OpenVPN
    sliceCaType: Local
  sliceIpamType: Local
  clusters:
    - worker-1
    - worker-2
    - worker-3
  qosProfileDetails:
    queueType: HTB
    priority: 1
    tcType: BANDWIDTH_CONTROL
    bandwidthCeilingKbps: 5120
    bandwidthGuaranteedKbps: 2560
    dscpClass: AF11
  namespaceIsolationProfile:
    applicationNamespaces:
    - namespace: cockroachdb
      clusters:
      - worker-1
      - worker-2
      - worker-3
    isolationEnabled: false                   #make this true in case you want to enable isolation
    allowedNamespaces:
     - namespace: kube-system
       clusters:
       - worker-1
       - worker-2
       - worker-3
