replicaCount: 1

image:
  repository: iad.ocir.io/oracle/ateam/mushop-payment
  tag: 1.0.1
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 99m
    memory: 100Mi

securityContext:
  capabilities:
    drop:
      - all
    add:
      - NET_BIND_SERVICE
  readOnlyRootFilesystem: true

service:
  port: 80
