{{- if not .Values.global.oosBucketSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-bucket
  labels: {{ include "mushop.labels" . | nindent 4 }}
type: Opaque
data:
  region: {{ .Values.secrets.bucket.region | default "" | b64enc | default ("" | quote) }}
  name: {{ .Values.secrets.bucket.name | default "" | b64enc | default ("" | quote) }}
  namespace: {{ .Values.secrets.bucket.namespace | default "" | b64enc | default ("" | quote) }}
  parUrl: {{ .Values.secrets.bucket.par | default "" | b64enc | default ("" | quote) }}
{{ end }}