{{- if .Values.tags.streaming -}}
{{- if not (or .Values.global.ossStreamSecret .Values.global.osb.oss) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oss-connection
  labels: {{ include "mushop.labels" . | nindent 4 }}
type: Opaque
data:
  streamId: {{ .Values.secrets.streams.streamId | default "" | b64enc | default ("" | quote) }}
  messageEndpoint: {{ .Values.secrets.streams.messageEndpoint | default "" | b64enc | default ("" | quote) }}
{{- end -}}
{{- end -}}