apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edge-router.fullname" . }}
  labels:
{{ include "edge-router.labels" . | indent 4 }}
data:
{{ (tpl (.Files.Glob "config/traefik.toml").AsConfig . ) | indent 2 }}

