---
# tasks file for kubeslice-controller-ent

### Cert-manager installation ###

- name: Deploy cert-manager chart
  tags:
  - cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: "{{ helm_repo_name }}/cert-manager"
    release_namespace: cert-manager
    create_namespace: true
    values:
      installCRDs: true
    kubeconfig: "{{ clusters.controller.kubeconfig }}"

- tags:
  - cert-manager
  debug:
    msg: "Wait for cert-manager to be Running"

- name: wait
  ansible.builtin.pause:
    seconds: "{{ chart_deploy_timeout }}"


- name: Checking cert-manager pods
  tags:
  - cert-manager
  shell: "kubectl get pods -n cert-manager --kubeconfig={{ clusters.controller.kubeconfig }}"
  register: command_output
- debug: var=command_output.stdout_lines


###### Kubeslice controller installation ########

- name: fetching controller Cluster endpoint 
  tags:
  - kubeslice-controller
  kubernetes.core.k8s_cluster_info:
    kubeconfig: "{{ clusters.controller.kubeconfig }}"
    validate_certs: "{{ validate_certs }}"
  register: controller_host
- set_fact:
    controller_endpoint: "{{ controller_host.connection.host  }}" 
  tags:
  - kubeslice-controller

- name: changing cluster endpoints entry in values-ent.yaml file 
  tags:
  - kubeslice-controller
  lineinfile:
      path: files/values-ent.yaml
      regexp: 'endpoint:'
      line: "    endpoint: {{ clusters.controller.endpoint | default(controller_endpoint, true) }}"


- shell: helm show values {{ helm_repo_name }}/kubeslice-controller --version={{ clusters.controller.chart_version }} > files/charts_default_values/kubeslice-controller-values.yaml
  tags:
  - kubeslice-controller
- set_fact:
    kubeslice_controller_values: "{{ lookup('file', 'files/charts_default_values/kubeslice-controller-values.yaml') | from_yaml }}"
  tags:
  - kubeslice-controller

- name: Deploy kubeslice-controller
  tags:
  - kubeslice-controller
  kubernetes.core.helm:
    name: kubeslice-controller
    chart_ref: "{{ helm_repo_name }}/kubeslice-controller "
    chart_version: "{{ clusters.controller.chart_version }}"
    release_namespace: kubeslice-controller 
    create_namespace: true
    values:
      kubeslice:
        controller:
          image: "{{ item.operator.image | default(kubeslice_controller_values.kubeslice.controller.image, true) }}"
          tag: "{{ item.operator.tag | default(kubeslice_controller_values.kubeslice.controller.tag, true) }}"      
      imagePullSecrets:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
      global:
        profile:
          openshift: "{{ clusters.controller.openshift_cluster }}"
    values_files:
      - files/values-ent.yaml
    kubeconfig: "{{ clusters.controller.kubeconfig }}"

#Openshift
- name: giving privillage to serviceaccount of kubeslice-controller namespace
  ignore_errors: yes
  when : 
  - clusters.controller.openshift_cluster == true
  tags:
  - kubeslice-controller
  shell: "oc adm policy add-scc-to-group privileged system:serviceaccounts:kubeslice-controller --kubeconfig={{ clusters.controller.kubeconfig }}"

- name: assigning enforce privileged for kubeslice-controller namespace
  ignore_errors: yes
  when : 
  - clusters.controller.openshift_cluster == true
  tags: 
  - kubeslice-controller
  shell: "kubectl --kubeconfig={{ clusters.controller.kubeconfig }} label --overwrite ns kubeslice-controller pod-security.kubernetes.io/enforce=privileged"

- tags:
  - kubeslice-controller
  debug:
    msg: "Wait for controller pod to be Running"

- name: wait 
  ansible.builtin.pause:
    seconds: "{{ chart_deploy_timeout }}"

- name: pausing for controller pods to comeup
  shell: "sleep 1m"

- name: Checking controller pods
  tags:
  - kubeslice-controller
  shell: "kubectl get pods -n kubeslice-controller --kubeconfig={{ clusters.controller.kubeconfig }}"
  register: controller_pod
- debug: var=controller_pod.stdout_lines

- name: Checking Project namespace already existed or not 
  ignore_errors: yes
  tags:
  - project
  shell: "kubectl get project {{ clusters.controller.projectNamespace }} -n kubeslice-controller --kubeconfig={{ clusters.controller.kubeconfig }}| grep -o {{ clusters.controller.projectNamespace }} "
  register: project_validation

- name: Creating a Project namespace 
  tags:
  - project
  when: "'non-zero return code' in project_validation.msg"
  kubernetes.core.k8s:
    state: present
    # src: files/Projectname.yaml
    namespace: kubeslice-controller
    kubeconfig: "{{ clusters.controller.kubeconfig }}"
    validate_certs: "{{ validate_certs }}"
    definition: |
      apiVersion: controller.kubeslice.io/v1alpha1
      kind: Project
      metadata:
        name: {{ clusters.controller.projectNamespace }}
        namespace: kubeslice-controller
      spec:
        serviceAccount:
          readWrite:
            - admin-ui
    
- name: wait for 5 sec
  ansible.builtin.pause:
    seconds: 5

- name: Checking Project created by project-namespace 
  tags:
  - project
  shell: "kubectl get project -n kubeslice-controller --kubeconfig={{ clusters.controller.kubeconfig }}"
  register: project_sa
- debug: var=project_sa.stdout_lines
  tags:
  - project


#kubeslice-UI installation 

# Fetching helm values 
- shell: helm show values {{ helm_repo_name }}/kubeslice-ui --version={{ clusters.controller.Kubeslice_ui.chart_version }} > files/charts_default_values/kubeslice-ui-values.yaml
  tags:
  - kubeslice-ui
- set_fact:
    kubeslice_ui_values: "{{ lookup('file', 'files/charts_default_values/kubeslice-ui-values.yaml') | from_yaml }}"
  tags:
  - kubeslice-ui

- name: Deploy kubeslice-UI-manager
  tags:
  - kubeslice-ui
  kubernetes.core.helm:
    name: kubeslice-ui
    chart_ref: "{{ helm_repo_name }}/kubeslice-ui "
    chart_version: "{{ clusters.controller.Kubeslice_ui.chart_version }}" 
    release_namespace: kubeslice-controller 
    create_namespace: true
    kubeconfig: "{{ clusters.controller.kubeconfig }}"
    values:
      kubeslice:
        ui:
          image: "{{ clusters.controller.Kubeslice_ui.image | default(kubeslice_ui_values.kubeslice.ui.image, true) }}"
          tag: "{{ clusters.controller.Kubeslice_ui.tag | default(kubeslice_ui_values.kubeslice.ui.tag, true) }}"
        uiproxy:
          service:
            type: "{{ clusters.controller.Kubeslice_ui.service_type | default(kubeslice_ui_values.kubeslice.uiproxy.service.type, true) }}"
      imagePullSecrets: 
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
      global:
        profile:
          openshift: "{{ clusters.controller.openshift_cluster }}"
    # values_files:
    #   - files/kubeslice-manager.yaml

# - name: giving privillage to serviceaccount of kubeslice-controller
#   shell: "oc adm policy add-scc-to-user privileged -z default -n kubeslice-controller --kubeconfig={{ clusters.controller.kubeconfig }}"
#   tags:
#   - openshift

- tags:
  - kubeslice-ui
  debug:
    msg: "Wait for UI pod to be Running"

- name: wait 
  ansible.builtin.pause:
    seconds: "{{ chart_deploy_timeout }}"

- name: Checking controller pods
  tags:
  - kubeslice-ui
  shell: "kubectl get pods -n kubeslice-controller --kubeconfig={{ clusters.controller.kubeconfig }}"
  register: controller_pod
- debug: var=controller_pod.stdout_lines

#describe pod in Kubeslice-controller namespace
- no_log: true
  when: " enable_debug == true "
  tags: 
  - test
  ignore_errors: yes
  shell: kubectl describe pods -n kubeslice-controller --kubeconfig="{{ clusters.controller.kubeconfig }}"
  register: controller_pod_output
- name: Verifying kubeslice-controller pods status
  when: " enable_debug == true "
  tags: 
  - test
  ignore_errors: yes
  debug:
    msg: 
    - 'pods description in Kubeslice-controller Namespace in controller cluster  ->'
    - "{{ controller_pod_output.stdout_lines }}"
