# apiVersion: v1
# kind: Secret
# type: kubernetes.io/service-account-token
# metadata:
#  name: "mongodb-enterprise-operator-multi-cluster-tokens"
#  annotations:
#   kubernetes.io/service-account.name: “mongodb-enterprise-operator-multi-cluster”
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-enterprise-operator-multi-cluster-tokens
  annotations:
    kubernetes.io/service-account.name: mongodb-enterprise-operator-multi-cluster
type: kubernetes.io/service-account-token
