apiVersion: controller.kubeslice.io/v1alpha1
kind: SliceConfig
metadata: 
  name: telenor-obs
  namespace: kubeslice-avesha
spec:
  sliceSubnet: 172.20.0.0/16
  sliceType: Application
  sliceGatewayProvider:
    sliceGatewayType: OpenVPN
    sliceCaType: Local
  sliceIpamType: Local
  clusters:
    - worker-sno-1
    - worker-sno-2
  qosProfileDetails:
    queueType: HTB
    priority: 3                     #keep integer values from 0 to 3
    tcType: BANDWIDTH_CONTROL
    bandwidthCeilingKbps: 10240
    bandwidthGuaranteedKbps: 5120
    dscpClass: AF11
  namespaceIsolationProfile:
    namespaceIsolationProfile:
    isolationEnabled: false                   #make this true in case you want to enable isolation
    allowedNamespaces:
     - namespace: kube-system
       clusters:
       - '*'
