apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
{{ include "api.labels" . | indent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: 3000
