apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "assets.fullname" . }}-deploy-{{ .Release.Revision }}
  labels: {{ include "assets.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: {{ include "assets.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "deploy.js"]
          env:
            {{- include "assets.env.par" . | nindent 12 }}