apiVersion: v1
kind: ServiceAccount
metadata:
  name:  obs-studio-sa
  labels:
    account: obs-studio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: obs-studio
  name: obs-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obs-studio
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: obs-studio
    spec:
      serviceAccountName: obs-studio-sa      
      # imagePullSecrets:
      # - name: obs-studio-secret 
      containers:
      - env:
        - name: VNC_PASSWD
          value: "123456"     
        image: manishsonawane1998/docker-obs
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        name: docker-obs
        ports:
        - containerPort: 5901
---
apiVersion: v1
kind: Service
metadata:
  name: obs-ui
  labels:
    app: obs-studio
spec:
  type: NodePort
  ports:
  - name: vnc-port-tcp
    protocol: TCP
    port: 5901
    targetPort: 5901
  selector:
    app: obs-studio
