apiVersion: v1
kind: ServiceAccount
metadata:
  name:  stream-server-sa
  labels:
    account: stream-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stream-server
  name: stream-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stream-server
    spec:
      serviceAccountName: stream-server-sa       
      #imagePullSecrets:
      #- name: stream-server-secret 
      containers:
      - image: pluot/nginx-rtmp 
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        name: nginx-rtmp
        ports:
        - containerPort: 1935
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stream-server-service
  labels:
    app: stream-server
spec:
  type: NodePort
  ports:
  - protocol: TCP
    name: rtmp
    port: 1935
    targetPort: 1935
  - protocol: TCP
    name: nginx
    port: 80
    targetPort: 80
  selector:
    app: stream-server
