apiVersion: networking.kubeslice.io/v1beta1
kind: ServiceExport
metadata:
  name: stream-server
spec:
  slice: media-slice
  selector:
    matchLabels:
      app: stream-server
  ports:
  - name: tcp
    containerPort: 1935
    protocol: TCP
